### ISSUE TITLE
No users configured but authentication required 

### ISSUE THREAD

**Issue by schlamar** [micromata/dave#16] opened 2020-05-23 10:48 UTC
If no users are configured I'm getting an authentication popup from my browser

**Comment by chclaus** [comment] 2020-08-03 22:01
Hej @schlamar,

sorry for delay. Had a lot of work... Did you also remove the `users:` parent element?

Best,
Christian

**Comment by schlamar** [comment] 2020-08-04 11:48
>Did you also remove the users: parent element?

I guess. Is that the issue?

**Comment by chclaus** [comment] 2020-08-04 18:04
Hmm.... I first thought so. But can't reproduce it. What client are you using?

**Comment by schlamar** [comment] 2020-08-05 07:04
Mhh if I remember correctly I tried various clients, including directly in the browser (Google Chrome).

**Comment by chclaus** [comment] 2021-04-07 16:00
I close the Issue, due to the past time

**Closed by chclaus** 2021-04-07 16:00 UTC
